server: 
  port: 8087

spring:
  r2dbc:
    url: r2dbc:mysql://localhost:3306/as_authuser
    username: root
    password: root



logging:
  level:
    web: debug
    io:
      r2dbc:
        pool: debug


